version: '3'

services:
  site:
    build: .
    container_name: card
    ports:
      - "80:80"
    restart: always
    environment:
      - VIRTUAL_HOST=hi.sepezho.com        # Your domain
      - LETSENCRYPT_HOST=hi.sepezho.com     # The domain name for Let's Encrypt SSL
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}  # Use the secret from GitHub
  
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 card
