version: '3'

services:
  site:
    build: .
    container_name: card
    ports:
      - "8080:80"
    restart: always
    environment:
      - VIRTUAL_HOST=hi.sepezho.com        # Your domain
      - LETSENCRYPT_HOST=hi.sepezho.com     # The domain name for Let's Encrypt SSL
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}  # Use the secret from GitHub

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /etc/nginx/certs
      - /etc/nginx/conf.d
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/nginx/certs:/etc/nginx/certs:rw
    restart: always

